service: serverless-aliyun-hello-world

provider:
  name: aliyun
  runtime: nodejs10
  credentials: ~/.aliyun_credentials

plugins:
  - serverless-aliyun-function-compute

package:
  exclude:
    - package-lock.json
    - .gitignore
    - .git/**

functions:
  hello:
    handler: index.hello
    events:
      - http:
          path: /foo
          method: get
