service: serverless-opensearch-api

provider:
  name: aliyun
  runtime: nodejs10
  credentials: ~/.aliyun_credentials
  region: cn-shanghai
  environment:
    OPENSEARCH_ACCESS_KEY_ID: ${env:OPENSEARCH_ACCESS_KEY_ID}
    OPENSEARCH_ACCESS_KEY_SECRET: ${env:OPENSEARCH_ACCESS_KEY_SECRET}
    OPENSEARCH_HOST: ${env:OPENSEARCH_HOST, 'opensearch.ap-southeast-1.aliyuncs.com'}
    OPENSEARCH_APP_NAME: ${env:OPENSEARCH_APP_NAME}

plugins:
  - serverless-aliyun-function-compute

package:
  exclude:
    - package-lock.json
    - .gitignore
    - .git/**
    - src/**
    - node_modules/**
    - tsconfig.json
    - index.d.ts
    - deploy.sh
    - .env
  include:
    - index.js
    - lib/**

functions:
  search:
    handler: index.hello
    events:
      - http:
          path: /api/search
          method: get
      - http:
          path: /api/search/recommendations
          method: get
      - http:
          path: /api/search/trending
          method: get
    initializer: null
    description: OpenSearch API for product search and recommendations
    memorySize: 512
    timeout: 10
