# serverless.yml

service: alibaba-nodejs-ts

provider:
  name: aliyun
  runtime: nodejs14
  credentials: ~/.aliyun/credentials # Path to your Alibaba Cloud credentials file
  region: cn-hangzhou

plugins:
  - serverless-aliyun-function-compute
  - serverless-typescript

package:
  excludeDevDependencies: true
  include:
    - src/**
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          path: hello
          method: get