service: serverless-aliyun-hello-world

provider:
  name: aliyun
  runtime: nodejs10
  credentials: ~/.aliyun_credentials
  region: cn-shanghai # Default region, can be overridden

plugins:
  - serverless-aliyun-function-compute

package:
  exclude:
    - package-lock.json
    - .gitignore
    - .git/**
    - src/**
    - node_modules/**
    - lib/**
    - tsconfig.json
    - index.d.ts
  include:
    - index.js

functions:
  hello:
    handler: index.hello
    events:
      - http:
          path: /foo
          method: get
    initializer: null # Explicitly set to null if not needed
    description: Hello World serverless function for Alibaba Cloud
